import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate } from 'react-router-dom'
import './styles.css'

const destinations = [
  { id: 1, name: 'Cox’s Bazar', country: 'Bangladesh', category: 'Beach', rating: 4.9, image: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1200&q=85', blurb: 'Endless shoreline, soft sunsets and coastal calm.' },
  { id: 2, name: 'Sajek Valley', country: 'Bangladesh', category: 'Mountain', rating: 4.8, image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=85', blurb: 'Wake above a rolling sea of clouds.' },
  { id: 3, name: 'Santorini', country: 'Greece', category: 'Island', rating: 4.9, image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=85', blurb: 'Whitewashed villages over the Aegean.' },
  { id: 4, name: 'Bali', country: 'Indonesia', category: 'Culture', rating: 4.7, image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=85', blurb: 'Temples, rice terraces, and ocean days.' },
]
const packages = [
  { id: 1, title: 'Cox’s Bazar Coastal Escape', place: 'Cox’s Bazar', duration: '3 days · 2 nights', price: 12400, rating: 4.9, image: destinations[0].image, tag: 'Best seller', itinerary: ['Airport pickup and beach sunset', 'Himchari waterfall & Inani beach', 'Breakfast and return transfer'] },
  { id: 2, title: 'Sajek Cloud Retreat', place: 'Sajek Valley', duration: '2 days · 1 night', price: 8900, rating: 4.8, image: destinations[1].image, tag: 'Weekend', itinerary: ['Khagrachari pickup', 'Ruilui Para and sunset viewpoint', 'Morning clouds and return'] },
  { id: 3, title: 'Santorini Blue Hour', place: 'Santorini', duration: '5 days · 4 nights', price: 87900, rating: 4.9, image: destinations[2].image, tag: 'International', itinerary: ['Welcome at Fira', 'Oia village and caldera cruise', 'Wine tasting & free day', 'Beach day', 'Airport transfer'] },
]
const hotels = [
  { id: 1, name: 'Sea Pearl Beach Resort', place: 'Cox’s Bazar', price: 6200, rating: 4.7, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=85' },
  { id: 2, name: 'Megh Machang Retreat', place: 'Sajek Valley', price: 4800, rating: 4.6, image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=85' },
  { id: 3, name: 'Aegean Pearl Suites', place: 'Santorini', price: 21300, rating: 4.9, image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1200&q=85' },
]
const money = v => new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT', maximumFractionDigits: 0 }).format(v)

function App() {
  const [wishlist, setWishlist] = useState([])
  const [booking, setBooking] = useState(null)
  const [bookings, setBookings] = useState([])
  const [query, setQuery] = useState('')
  const toggleWish = id => setWishlist(x => x.includes(id) ? x.filter(a => a !== id) : [...x, id])
  const confirmBooking = (item, type) => { setBookings(x => [{ ...item, type, reference: `TRV-${String(x.length + 1048)}` }, ...x]); setBooking(null) }
  return <><Header query={query} setQuery={setQuery} wishlist={wishlist}/><main><Routes>
    <Route path="/" element={<Home query={query} wishlist={wishlist} toggleWish={toggleWish} setBooking={setBooking}/>} />
    <Route path="/destinations" element={<Explore query={query} wishlist={wishlist} toggleWish={toggleWish}/>} />
    <Route path="/packages" element={<Packages setBooking={setBooking}/>} />
    <Route path="/hotels" element={<Hotels setBooking={setBooking}/>} />
    <Route path="/bookings" element={<Bookings bookings={bookings}/>} />
    <Route path="/wishlist" element={<Explore wishlist={wishlist} toggleWish={toggleWish} onlySaved/>} />
    <Route path="/admin" element={<Admin bookings={bookings}/>} />
    <Route path="*" element={<Home query={query} wishlist={wishlist} toggleWish={toggleWish} setBooking={setBooking}/>} />
  </Routes></main><Footer/>{booking && <Checkout item={booking.item} type={booking.type} close={() => setBooking(null)} confirm={confirmBooking}/>}</>
}
function Header({query, setQuery, wishlist}) { const navigate = useNavigate(); return <header><Link className="brand" to="/"><span>✦</span> travio</Link><nav><NavLink to="/destinations">Explore</NavLink><NavLink to="/packages">Tours</NavLink><NavLink to="/hotels">Hotels</NavLink><NavLink to="/bookings">My trips</NavLink></nav><div className="head-actions"><button className="search" onClick={() => navigate('/destinations')}>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Where to?"/></button><Link className="heart" to="/wishlist">♡<i>{wishlist.length}</i></Link><Link className="profile" to="/admin">AR</Link></div></header> }
function Home({query, wishlist, toggleWish, setBooking}) { return <><section className="hero"><div className="hero-copy"><p className="eyebrow">YOUR NEXT STORY STARTS HERE</p><h1>Find the places<br/><em>that move you.</em></h1><p className="lead">Curated escapes, seamless bookings, and memories that stay with you long after you return.</p><Link className="primary" to="/destinations">Explore destinations <span>→</span></Link></div><div className="hero-card"><div className="hero-image"/><div className="float-card"><span>✦ Handpicked for you</span><strong>Sajek Valley</strong><small>Bangladesh · Mountain escape</small><div><b>4.8 ★</b><Link to="/packages">View trip →</Link></div></div></div><div className="hero-wave"/></section><section className="section"><div className="section-title"><div><p className="eyebrow">DISCOVER THE WORLD</p><h2>Places worth going <em>out of your way for.</em></h2></div><Link to="/destinations">View all destinations →</Link></div><div className="destination-grid">{destinations.slice(0,3).filter(d=>!query || `${d.name} ${d.country}`.toLowerCase().includes(query.toLowerCase())).map(d=><DestinationCard d={d} saved={wishlist.includes(d.id)} toggleWish={toggleWish} key={d.id}/>)}</div></section><section className="accent-section"><div><p className="eyebrow">TRAVEL MADE SIMPLE</p><h2>One place.<br/><em>Every journey.</em></h2></div><div className="benefits"><article><span>◌</span><h3>Curated stays</h3><p>Thoughtful hotels and homestays for every kind of traveler.</p></article><article><span>◈</span><h3>Book with ease</h3><p>Simple, secure booking from inspiration to itinerary.</p></article><article><span>⌁</span><h3>Here for you</h3><p>Friendly support whenever the road gets complicated.</p></article></div></section><section className="section"><div className="section-title"><div><p className="eyebrow">FIND YOUR ESCAPE</p><h2>Trending <em>journeys.</em></h2></div><Link to="/packages">See all tours →</Link></div><div className="package-grid">{packages.map(p=><PackageCard p={p} setBooking={setBooking} key={p.id}/>)}</div></section></> }
function DestinationCard({d, saved, toggleWish}) { return <article className="destination-card"><img src={d.image} alt={d.name}/><button className={'save '+(saved?'saved':'')} onClick={()=>toggleWish(d.id)}>{saved?'♥':'♡'}</button><div><span>{d.country} · {d.category}</span><h3>{d.name}</h3><p>{d.blurb}</p><b>{d.rating} ★</b></div></article> }
function Explore({query='', wishlist, toggleWish, onlySaved=false}) { const items=destinations.filter(d => (!onlySaved || wishlist.includes(d.id)) && (!query || `${d.name} ${d.country} ${d.category}`.toLowerCase().includes(query.toLowerCase()))); return <PageIntro eyebrow={onlySaved?'YOUR COLLECTION':'EXPLORE DESTINATIONS'} title={onlySaved?'Saved places':'A world of possibilities'} text={onlySaved?'Places you want to return to, all in one place.':'Search destinations by country, city, or category.'}><div className="filterbar"><span>⌕</span><input placeholder="Search destinations" defaultValue={query}/><button>All categories⌄</button></div><div className="destination-grid full">{items.length?items.map(d=><DestinationCard d={d} saved={wishlist.includes(d.id)} toggleWish={toggleWish} key={d.id}/>):<Empty text="No saved destinations yet. Explore a place and tap the heart to keep it here."/>}</div></PageIntro> }
function Packages({setBooking}) { return <PageIntro eyebrow="TOUR PACKAGES" title="Go somewhere wonderful." text="Every package includes a considered itinerary, clear pricing, and a little room for surprise."><div className="package-grid full">{packages.map(p=><PackageCard p={p} setBooking={setBooking} key={p.id}/>)}</div></PageIntro> }
function PackageCard({p,setBooking}) { return <article className="package-card"><div className="package-image"><img src={p.image} alt=""/><span>{p.tag}</span></div><div className="package-body"><small>{p.place}</small><h3>{p.title}</h3><p>{p.duration} <b>· {p.rating} ★</b></p><div className="card-bottom"><strong>{money(p.price)} <small>/ person</small></strong><button onClick={()=>setBooking({item:p,type:'Tour package'})}>Book now →</button></div></div></article> }
function Hotels({setBooking}) { return <PageIntro eyebrow="STAY A WHILE" title="Hotels that feel right." text="Reserve places to rest, recharge, and wake up somewhere new."><div className="hotel-grid">{hotels.map(h=><article className="hotel-card" key={h.id}><img src={h.image} alt=""/><div><span>{h.place}</span><h3>{h.name}</h3><p>{h.rating} ★ · Free cancellation available</p><div><strong>{money(h.price)} <small>/ night</small></strong><button onClick={()=>setBooking({item:h,type:'Hotel reservation'})}>Reserve →</button></div></div></article>)}</div></PageIntro> }
function Bookings({bookings}) { return <PageIntro eyebrow="MY TRIPS" title="Your journeys, together." text="Bookings, confirmations, and the road ahead."><div className="booking-list">{bookings.length?bookings.map((b,i)=><article className="booking" key={i}><img src={b.image}/><div><span>{b.type} · Confirmed</span><h3>{b.title || b.name}</h3><p>Reference {b.reference} · {b.duration || `${money(b.price)} per night`}</p></div><b>Confirmed ✓</b></article>):<Empty text="You do not have any bookings yet. Your next adventure is waiting."/>}</div></PageIntro> }
function Admin({bookings}) { return <PageIntro eyebrow="ADMIN DASHBOARD" title="Keep Travio moving." text="A clear view of the platform. Production administration is protected by a JWT role check."><div className="stats"><div><span>Total travellers</span><strong>1,284</strong><small>+12% this month</small></div><div><span>Active packages</span><strong>24</strong><small>Across 8 destinations</small></div><div><span>Hotel partners</span><strong>16</strong><small>4 awaiting review</small></div><div><span>Bookings today</span><strong>{bookings.length + 8}</strong><small>All payments secured</small></div></div><div className="admin-table"><h3>Recent bookings</h3>{[...bookings, ...packages].slice(0,4).map((b,i)=><p key={i}><span>{b.title || b.name}</span><small>{b.reference || 'TRV-10'+(48+i)}</small><b>Confirmed</b></p>)}</div></PageIntro> }
function Checkout({item,type,close,confirm}) { const [done,setDone]=useState(false); return <div className="modal-backdrop"><div className="checkout">{done?<div className="success"><span>✓</span><h2>You’re going places!</h2><p>Your booking is confirmed. A receipt and travel details will appear in My trips.</p><button className="primary" onClick={close}>Done</button></div>:<><button className="close" onClick={close}>×</button><p className="eyebrow">SECURE CHECKOUT</p><h2>Ready when you are.</h2><div className="checkout-item"><img src={item.image}/><div><small>{type}</small><h3>{item.title || item.name}</h3><b>{money(item.price)}</b></div></div><label>Traveller name<input placeholder="Your full name"/></label><label>Email address<input type="email" placeholder="you@example.com"/></label><label>Payment method<select><option>Demo card payment</option><option>Mobile banking</option></select></label><button className="primary fullbutton" onClick={()=>{confirm(item,type);setDone(true)}}>Confirm & pay {money(item.price)} →</button><small className="secure">🔒 Payments are simulated in this demo. Connect a payment gateway for production.</small></>}</div></div> }
function PageIntro({eyebrow,title,text,children}) { return <section className="page"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-lead">{text}</p>{children}</section> }
function Empty({text}) { return <div className="empty"><span>✦</span><p>{text}</p><Link className="primary" to="/destinations">Explore destinations</Link></div> }
function Footer(){return <footer><Link className="brand" to="/"><span>✦</span> travio</Link><p>Travel with intention. See more, feel more, come back changed.</p><div><Link to="/packages">Tours</Link><Link to="/hotels">Hotels</Link><Link to="/admin">Admin</Link></div><small>© 2026 Travio. Made for curious travellers.</small></footer>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>)
